### ISSUE TITLE
cannot import name 'cydot' from partially initialized module 'cylp.cy.CyClpSimplex'

### ISSUE THREAD

**Issue by chiga17** [coin-or/coin-or.github.io#4]
I cannot run example from this page: https://coin-or.github.io/CyLP/modules/CyCoinPackedMatrix.html.
OS: Win10
Python 3.9
cylp 0.92.1

More info below:

```
PS C:\...\>

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19044.0 Microsoft Windows NT 10.0.19044.0


PS C:\...\> python --version
Python 3.9.0
PS C:\...\> python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cylp
>>> cylp.__version__
'0.92.1'
>>> import cylp.cy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\app\python39\lib\site-packages\cylp\cy\__init__.py", line 2, in <module>
    from .CyClpSimplex import CyClpSimplex
  File "cylp\\cy\\CyClpSimplex.pyx", line 1, in init cylp.cy.CyClpSimplex
  File "cylp\\cy\\CyClpPrimalColumnPivotBase.pyx", line 1, in init cylp.cy.CyClpPrimalColumnPivotBase
  File "cylp\\cy\\CyClpDualRowPivotBase.pyx", line 1, in init cylp.cy.CyClpDualRowPivotBase
  File "cylp\\cy\\CyOsiSolverInterface.pyx", line 1, in init cylp.cy.CyOsiSolverInterface
  File "cylp\\cy\\CyCbcModel.pyx", line 1, in init cylp.cy.CyCbcModel
  File "cylp\\cy\\CyOsiCuts.pyx", line 3, in init cylp.cy.CyOsiCuts
  File "c:\app\python39\lib\site-packages\cylp\py\__init__.py", line 1, in <module>
    from . import pivots
  File "c:\app\python39\lib\site-packages\cylp\py\pivots\__init__.py", line 3, in <module>
    from .PositiveEdgePivot import PositiveEdgePivot
  File "c:\app\python39\lib\site-packages\cylp\py\pivots\PositiveEdgePivot.py", line 10, in <module>
    from cylp.cy.CyClpSimplex import cydot
ImportError: cannot import name 'cydot' from partially initialized module 'cylp.cy.CyClpSimplex' (most likely due to a circular import) (c:\app\python39\lib\site-packages\cylp\cy\CyClpSimplex.cp39-win_amd64.pyd)    
>>>
```

**Comment by chiga17** [comment]
seems wrong repo
